# Generated by Django 6.0.6 on 2026-07-30 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotel_hotel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='category',
            field=models.CharField(choices=[('RESORT', 'Resort'), ('CABIN', 'Cabin'), ('VILLA', 'Villa'), ('HOTEL', 'Hotel'), ('APARTMENT', 'Apartment'), ('HOMESTAY', 'Homestay'), ('GUEST_HOUSE', 'Guest House'), ('OTHER', 'Other')], default='HOTEL', max_length=20),
        ),
    ]
