# Generated by Django 6.0.6 on 2026-07-21 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_payment_provider_reference_payment_provider_response_and_more'),
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='hotels.hotel'),
        ),
        migrations.AddField(
            model_name='payment',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='hotels.hotel'),
        ),
    ]
