# Generated by Django 6.0.6 on 2026-07-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100)),
                ('guest_phone', models.CharField(blank=True, max_length=20)),
                ('guest_email', models.CharField(max_length=100, unique=True)),
                ('id_number', models.CharField(max_length=50, unique=True)),
                ('nationality', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'guest',
            },
        ),
    ]
