# Generated by Django 6.0.6 on 2026-08-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_alter_guest_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
