# Generated by Django 6.0.6 on 2026-07-15 23:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0001_initial'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('comments', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='guests.guest')),
                ('resv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='reservations.reservation')),
            ],
            options={
                'db_table': 'feedback',
                'unique_together': {('guest', 'resv')},
            },
        ),
    ]
