"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import sys
from pathlib import Path

from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
_DEFAULT_DEV_SECRET = "django-insecure-01ky-fhel2(q*!u&v4dj6vc(ivnq*vzxi0p9jtebl#g)_fr7i6"
SECRET_KEY = config("SECRET_KEY", default=_DEFAULT_DEV_SECRET)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=True, cast=bool)

# Fail loudly instead of serving production traffic with the known dev key.
if not DEBUG and SECRET_KEY == _DEFAULT_DEV_SECRET:
    sys.stderr.write(
        "ERROR: DEBUG=False requires a real SECRET_KEY in the environment. "
        "Set SECRET_KEY before starting the server.\n"
    )
    sys.exit(1)

ALLOWED_HOSTS = [
    host.strip()
    for host in config("ALLOWED_HOSTS", default="*").split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticiles",
    "rest_framework",
    "corsheaders",
    "django_filters",
    "drf_spectacular",
    "apps.accounts",
    "apps.hotels",
    "apps.rooms",
    "apps.guests",
    "apps.reservations",
    "apps.services",
    "apps.billing",
    "apps.feedback",
    "apps.notifications",
    "apps.mobile",
    "frontend",

]
AUTH_USER_MODEL = "accounts.Staff"

# Authenticate staff users (accounts.Staff via Django's ModelBackend) and
# public web guests (apps.guests.Guest via GuestBackend). GuestBackend returns
# a GuestUser adapter that keeps guests out of the staff table/roster.
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "apps.guests.auth.GuestBackend",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    # Serves /static/ directly from gunicorn (no nginx needed) in all envs.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "frontend" / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'frontend.context_processors.stayhub_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DB_ENGINE = config("DB_ENGINE", default="sqlite").lower()
if DB_ENGINE in {"postgres", "postgresql"}:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": config("DB_NAME"),
            "USER": config("DB_USER"),
            "PASSWORD": config("DB_PASSWORD", default=""),
            "HOST": config("DB_HOST", default="127.0.0.1"),
            "PORT": config("DB_PORT", default="5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "frontend" / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# WhiteNoise: serve collected static files with gzip/brotli compression.
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend"
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}
 
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:8000",
]
CORS_ALLOW_ALL_ORIGINS = True

# ── Base URL ────────────────────────────────────────────────────
# Set BASE_URL in .env to the public origin of your deployment
# (e.g. https://your-tunnel.devtunnels.ms or https://your-domain.com).
# Changing this ONE value re-points Paystack (return + webhook),
# Google OAuth redirect URIs, CSRF trusted origins, and every
# externally-visible URL to the new host.
BASE_URL = config("BASE_URL", default="http://localhost:8000").rstrip("/")

# CSRF_TRUSTED_ORIGINS defaults to localhost + the BASE_URL host
# so a single .env change keeps CSRF working on the new domain too.
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in config(
        "CSRF_TRUSTED_ORIGINS",
        default=f"http://localhost:8000,{BASE_URL}",
    ).split(",")
    if origin.strip()
]

BREVO_API_KEY = config("BREVO_API_KEY", default="")
BREVO_SMS_SENDER = config("BREVO_SMS_SENDER", default="StayHub")

PAYSTACK_SECRET_KEY = config("PAYSTACK_SECRET_KEY", default="")
PAYSTACK_PUBLIC_KEY = config("PAYSTACK_PUBLIC_KEY", default="")
PAYSTACK_RETURN_URL = config("PAYSTACK_RETURN_URL", default=f"{BASE_URL}/booking/")
PAYSTACK_WEBHOOK_URL = config("PAYSTACK_WEBHOOK_URL", default=f"{BASE_URL}/api/billing/paystack/webhook/")
DELIVERED_URL = BASE_URL  # deprecated alias, keep for compatibility

# Development mail is printed to the terminal.  Set EMAIL_BACKEND to Django's
# SMTP backend and the SMTP_* variables in the deployment environment to send
# real password-reset and two-step-verification messages.
EMAIL_BACKEND = (
    config("EMAIL_BACKEND", default="django.core.mail.backends.console.EmailBackend")
)
EMAIL_HOST = config("SMTP_HOST", default="")
EMAIL_PORT = config("SMTP_PORT", default=587, cast=int)
EMAIL_HOST_USER = config("SMTP_USERNAME", default="")
EMAIL_HOST_PASSWORD = config("SMTP_PASSWORD", default="")
EMAIL_USE_TLS = config("SMTP_USE_TLS", default=True, cast=bool)
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="StayHub <no-reply@stayhub.local>")

# Google OAuth is deliberately environment-configured: never commit a client
# secret to source control.  The redirect URI must exactly match Google Cloud.
GOOGLE_OAUTH_CLIENT_ID = config("GOOGLE_OAUTH_CLIENT_ID", default="")
GOOGLE_OAUTH_CLIENT_SECRET = config("GOOGLE_OAUTH_CLIENT_SECRET", default="")
GOOGLE_OAUTH_REDIRECT_URI = config(
    "GOOGLE_OAUTH_REDIRECT_URI",
    default=f"{BASE_URL}/api/auth/google/callback/",
)
# If GOOGLE_OAUTH_REDIRECT_URIS isn't set, build a sensible default from
# BASE_URL so a single .env change re-points Google sign-in too.
GOOGLE_OAUTH_REDIRECT_URIS = [
    value.strip()
    for value in config(
        "GOOGLE_OAUTH_REDIRECT_URIS",
        default=f"http://localhost:8000/api/auth/google/callback/,{BASE_URL}/api/auth/google/callback/",
    ).split(",")
    if value.strip()
]
ADMIN_SIGNUP_KEY = config("ADMIN_SIGNUP_KEY", default="")


