# Generated by Django 6.0.6 on 2026-07-21 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
        ('reservations', '0002_reservation_hotel'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='hotels.hotel'),
        ),
        migrations.AddField(
            model_name='room',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='room',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_rooms', to='reservations.reservation'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='hotels.hotel'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='type_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='roomtype',
            constraint=models.UniqueConstraint(fields=('hotel', 'type_name'), name='room_type_hotel_name_unique'),
        ),
    ]
