# Generated by Django 6.0.6 on 2026-08-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_maintenance_hotel_room_price_per_night_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.CharField(blank=True, default='', help_text='Static image path, e.g. frontend/img/xxx.jpg', max_length=255),
        ),
    ]
